name: Dart Format Check (On Label)

on:
  pull_request:
    types: [labeled]

jobs:
  format-check:
    if: ${{ github.event.label.name == 'run-format-check' }}
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          flutter-version: 3.29.3
          cache: true

      - name: 🌋 Flutter pub get 
        run: flutter pub get

      - name: ✨ Flutter pub analyze
        run: flutter analyze