// Mocks generated by Mockito 5.4.4 from annotations
// in products_crud/test/bloc/product_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:products_crud/domain/product/model/product_details.dart' as _i2;
import 'package:products_crud/domain/product/use_case/get_product_details_use_case.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductDetails_0 extends _i1.SmartFake
    implements _i2.ProductDetails {
  _FakeProductDetails_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetProductDetailsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductDetailsUseCase extends _i1.Mock
    implements _i3.GetProductDetailsUseCase {
  MockGetProductDetailsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ProductDetails> call(int? id) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [id],
        ),
        returnValue: _i4.Future<_i2.ProductDetails>.value(_FakeProductDetails_0(
          this,
          Invocation.method(
            #call,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.ProductDetails>);
}
