name: products_crud
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  auto_route: ^9.2.2
  freezed_annotation: ^2.4.4
  easy_localization: ^3.0.7
  intl: ^0.19.0
  logger: ^2.3.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.1.1
  injectable: ^2.5.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.4
  cached_network_image: ^3.4.1
  ionicons: ^0.2.2
  google_fonts: ^6.2.1
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.4.13
  mockito: ^5.4.4
  freezed: ^2.5.2
  very_good_analysis: ^6.0.0
  bloc_test: ^9.1.7
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/lottie/