# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProductsCrud' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  source 'https://github.com/CocoaPods/Specs.git'

  # Pods for ProductsCrud

  target 'ProductsCrudTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductsCrudUITests' do
    # Pods for testing
  end

  # Swinject - DI
  pod 'Swinject', '~> 2.9.1'
  
  # Linter
  pod 'SwiftLint', '~> 0.57.0'
end
